IF DB_ID('EMDS') IS NULL CREATE DATABASE EMDS;
IF DB_ID('EMDS_ARCHIVE') IS NULL CREATE DATABASE EMDS_ARCHIVE;
IF DB_ID('ETS_V5') IS NULL CREATE DATABASE ETS_V5;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'emds_reader')
  CREATE LOGIN emds_reader WITH PASSWORD = '__READER_PASSWORD__', CHECK_POLICY = ON;
GO
USE EMDS;
GO

CREATE TABLE ACCOUNTING_GROUP (
  GRUP_ID INT IDENTITY(1,1) PRIMARY KEY,
  GRUP_KODU VARCHAR(20) NOT NULL,
  GRUP_ADI NVARCHAR(200) NOT NULL,
  ACIKLAMA NVARCHAR(500) NULL,
  OLUSTURMA_TARIHI DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE ACCOUNTING_COMPANY (
  FIRMA_ID INT IDENTITY(1,1) PRIMARY KEY,
  FIRMA_KODU VARCHAR(20) NOT NULL,
  UNVAN NVARCHAR(300) NOT NULL,
  VERGI_NO VARCHAR(20) NULL,
  ACIKLAMA NVARCHAR(500) NULL,
  OLUSTURMA_TARIHI DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE ACCOUNTING_BRANCH (
  SUBE_ID INT IDENTITY(1,1) PRIMARY KEY,
  SUBE_KODU VARCHAR(20) NOT NULL,
  SUBE_ADI NVARCHAR(200) NOT NULL,
  GRUP_ID INT NULL REFERENCES ACCOUNTING_GROUP(GRUP_ID),
  FIRMA_ID INT NULL REFERENCES ACCOUNTING_COMPANY(FIRMA_ID),
  ACIKLAMA NVARCHAR(500) NULL,
  OLUSTURMA_TARIHI DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE APPCARD_VIRTUAL (
  KART_ID INT IDENTITY(1,1) PRIMARY KEY,
  KART_NO VARCHAR(30) NOT NULL,
  SUBE_ID INT NULL REFERENCES ACCOUNTING_BRANCH(SUBE_ID),
  AKTIF BIT NOT NULL DEFAULT 1,
  ACIKLAMA NVARCHAR(500) NULL,
  OLUSTURMA_TARIHI DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE ACCOUNTING_RECEIPT (
  FIS_ID INT IDENTITY(1,1) PRIMARY KEY,
  FIS_NO VARCHAR(30) NOT NULL,
  FIS_TARIHI DATETIME2 NOT NULL,
  SUBE_ID INT NULL REFERENCES ACCOUNTING_BRANCH(SUBE_ID),
  FIRMA_ID INT NULL REFERENCES ACCOUNTING_COMPANY(FIRMA_ID),
  GRUP_ID INT NULL REFERENCES ACCOUNTING_GROUP(GRUP_ID),
  FIS_ACIKLAMASI NVARCHAR(1000) NULL,
  TOPLAM_TUTAR DECIMAL(18,2) NOT NULL DEFAULT 0,
  OLUSTURMA_TARIHI DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE ACCOUNTING_RECEIPT_DETAIL (
  DETAY_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
  FIS_ID INT NOT NULL REFERENCES ACCOUNTING_RECEIPT(FIS_ID),
  SATIR_NO INT NOT NULL,
  HESAP_KODU VARCHAR(30) NOT NULL,
  BORC DECIMAL(18,2) NOT NULL DEFAULT 0,
  ALACAK DECIMAL(18,2) NOT NULL DEFAULT 0,
  SATIR_ACIKLAMASI NVARCHAR(1000) NULL,
  KAYIT_TARIHI DATETIME2 NOT NULL
);
GO

CREATE USER emds_reader FOR LOGIN emds_reader;
ALTER ROLE db_datareader ADD MEMBER emds_reader;
GO

USE EMDS_ARCHIVE;
GO
CREATE USER emds_reader FOR LOGIN emds_reader;
ALTER ROLE db_datareader ADD MEMBER emds_reader;
GO

USE ETS_V5;
GO
CREATE USER emds_reader FOR LOGIN emds_reader;
ALTER ROLE db_datareader ADD MEMBER emds_reader;
GO

